### ISSUE TITLE
Can get stuck inside a door

### ISSUE THREAD

**Issue by ad4mstewart** [SheerSt/pokewilds#150]
When building fences and adding doors for gates I found sometimes placing a door on the side of the fence it wont turn into a gate but will stay as a door and generate a 1x1 "house" you can enter. If you try to use cut on the door it breaks but the door but the pink floor indicating an entrance remains and you can still enter the 1x1 but wont be able to exit. Once stuck you cant open the menu.

**Comment by bolabolagoma** [comment]
hi im new to github but i have been playing this game, I also encountered this issue and found a fix, I don't know how you will implement it but apparently if you surround the carpet square with walls and cut the walls from the direction that you will enter the "house" you can get rid of the pink entrance floor

**Comment by TasteofPomegranate** [comment]
I had this same thing happen, but I accidentally saved my game when I closed the window.

Upon reloading the save, I am able to turn in place but if I try to move it just locks up again. I can open my menu and select different field moves, but unfortunately the only one that might get me free (teleport) is one I don't have a 'mon for at the moment because I dropped it off temporarily.

Pretty disappointing tbh, because my original save file corrupted and between the two different worlds I put in a lot of effort and I don't think I'll be making a third one.

**Comment by TasteofPomegranate** [comment]
Just an update on this; I tried replacing the 'game' file from the save where I got stuck (with the one from the first world that got corrupted), and it worked! Sort of. It spawned me in a completely random spot on the overworld, but my team has been replaced with the one from the corrupted save...which is fairly similar, but I did lose my shiny Soodowoodo :(

Edit: also replaced my inventory, which is a bit of a bummer as the corrupted world save file didn't have as many items. But it beats having an unplayable save.

Also, if this DOES happen to you, you CAN use teleport to get out of the black void, so I'd recommend keeping a teleport mon on you at all times.

**Comment by fourlastor** [comment]
@TasteofPomegranate thank you for helping others with this.
If you get stuck in a void, and the game doesn't respond, close the game. It will prompt you to save the game (save). When you reload, go into your inventory and use the `ESCAPE ROPE` object (it has infinite uses), it will bring you to the latest safe place.

@ad4mstewart @bolabolagoma this issue has been fixed in the latest [release](https://github.com/SheerSt/pokewilds/releases/tag/latest), so you will be able to build gates as you expect to!

**Comment by TasteofPomegranate** [comment]
@fourlastor I didn't even think of the escape rope! I will definitely keep that in mind for next time. Using teleport does also work, although that only works if you have a pokemon with the move in your party and a telepad to go to.
