### ISSUE TITLE
Unbreakable Red Door Entrance Tiles

### ISSUE THREAD

**Issue by Thibbs23** [SheerSt/pokewilds#161]
I I have encountered an issue where when I try to create a pen, it makes a red door entrance tile that I cannot get rid of. I have tried to dig, cut, and place other object on the tile and nothing has worked. I will provide an image with the red tiles on the left and the pens mirrored on the right side
![image](https://user-images.githubusercontent.com/113220615/189463829-8f0a23ef-1a70-4650-a2a3-e8366be22c51.jpg)

**Comment by Thibbs23** [comment]
Also, when I try to place a gate next to the tiles they turn into walls

**Comment by fourlastor** [comment]
@Thibbs23 thank you for reporting this

For the red tiles, you can fix them with the `pokewilds-dev.exe` version, which lets you "paint" tiles over others. 

For the main issue (not being able to create the fence), it's been fixed in the latest [release](https://github.com/SheerSt/pokewilds/releases/latest).

After downloading it, you can copy-paste your save files (they're folders called `yoursavenamehere.sav` within your game folder) from the old version to the new version and continue from there.
