### ISSUE TITLE
Game has trouble displaying uppercase "i"

### ISSUE THREAD

**Issue by HighFlyer-222** [SheerSt/pokewilds#243]
Sometimes it displays an X instead,
![drapxon](https://user-images.githubusercontent.com/66063913/200136387-bb174687-720d-457a-ba2b-06b2a0dcb451.png)

sometimes it.. gets stuck and stops rendering when it encounters the letter? dunno
![drap](https://user-images.githubusercontent.com/66063913/200136415-f3897ec3-514f-43d5-89da-57ba4af5bc24.png)

and then that remains on the screen for the rest of my life
![drap2](https://user-images.githubusercontent.com/66063913/200136426-e7c2e4b9-b88c-4288-aa67-22c1d505e5aa.png)

man what the hell man

**Comment by AndurinAadin** [comment]
> I have the exact same problem. The debug gives me this when in a fight with a pokemon with an uppercase "i":

com.pkmngen.game.DrawEnemyHealthGen2@1ccc1026
java.lang.NullPointerException

> And on top of that the game freezes when a pokemon levels up and the stat advancement window pops up. The game cannot render the "i" in "special" and stops at "spec":

https://user-images.githubusercontent.com/117555598/200153836-64d88894-24be-47a7-a1e1-ca130a42e2e3.png

Debug console:

com.pkmngen.game.GainExpAnimationGen2$ShowLevelUpStats@1a97c2b0
java.lang.NullPointerException

> Furthermore if a pokemon with the letter "i" in its name is caught, opening up the pokemon menu causes the game to freeze (The pokemon causing the exception here was a Miltank):

https://user-images.githubusercontent.com/117555598/200153812-af04541e-b94e-4c0d-a432-b244400b7d25.png

Debug console:

com.pkmngen.game.DrawPokemonMenu@492be039
java.lang.NullPointerException

> Installing the English language service pack is not an option because of the Single Language restriction of my version of Win.
I love what this game is aspiring to do and I want to be able to play it so bad, please help...

**Comment by HighFlyer-222** [comment]
Well what do you know - changing my system language to English worked. I wish there was a better way to fix this tho...

I think it was because uppercase i in Turkish is a special character (İ, not I) that the game can't actually display. idk how i never thought of that

**Comment by fourlastor** [comment]
@AndurinAadin @HighFlyer-222 this is an unfortunate bug in pokewilds with using turkish language - we're working on fixing it.

Instead of changing your system settings, for now you can use the following workaround (which will force only pokewilds to run in english):

1. Download the "otherplatforms" version from the [latest release](https://github.com/SheerSt/pokewilds/releases/latest).
2. Follow the instructions in the readme file (install java for windows)
3. Instead of running it by double clicking, do this:

- Open the folder containing pokewilds.jar
- Shift + right-click in the folder and select 'Open powershell window here'
- Type cmd in the window and press enter.
- Type `java -Duser.country=us -Duser.language=en -jar pokewilds.jar` into the window and press enter.
