### ISSUE TITLE
Couldn't create window

### ISSUE THREAD

**Issue by CynonMCC** [SheerSt/pokewilds#260]
I've just downloaded the win64 version of the game, tried to start it and this error showed up:

![image](https://user-images.githubusercontent.com/19671952/200301254-4eb048f2-a968-43cd-889f-f862f8673f00.png)
[error.log](https://github.com/SheerSt/pokewilds/files/9951046/error.log)

**Comment by alberto64674yt** [comment]
do you have java installed? because its weird i run without problems in my first time

**Comment by CynonMCC** [comment]
Yes, i've recently installed the java jdk-19 (latest version as of today):
![image](https://user-images.githubusercontent.com/19671952/200318085-14436cd7-fd4c-46ed-928d-80b12625ee85.png)
Install path: C:\Program Files\Java\jdk-19

**Comment by alberto64674yt** [comment]
wow thats weird then something is missing/not compatible to show that java error windows i hope the developers or some skilled one can help you because the game is very addicting

**Comment by CynonMCC** [comment]
I think i got it... i've installed it on my notebook and that worked fine... so i think the remote was the issue, because i've installed it on a remote controlled computer without real graphic card...

**Comment by UnspokenToken** [comment]
Was literally working for me yesterday, and then after a crash forcing me to restart and update (Windows 10) I started getting this error. Similar thing happened with minecraft java edition. Web apps that previously ran fine are now extremely laggy as well. Not to mention a bunch of settings changed. I hate automatic updates like this with a white hot passion. Gonna try rolling back my java version as I suspect it might have updated as well and might be what's breaking things...

EDIT: Nope that did nothing. :/

EDIT 2: System restore seems to have fixed the pokewilds bit at least. I guess minecraft actually happens to just be down right now according to https://downdetector.com/status/minecraft/ so I have no idea, but I garuntee it was whatever windows update was installed that broke pokewilds since the system restore worked fine.

**Comment by fourlastor** [comment]
@UnspokenToken this is usually an issue with graphic drivers not being installed/updated - so that might be what system restore did to fix the issue

@CynonMCC you could try running pokewilds via `pokewilds-compat.exe` (present from version `0.8.7`), this will run in a more compatible way (at the cost of some performances)

We always try to improve device compatibility, so make sure to check running the default file when a new version comes out

**Comment by git-pro-shivam** [comment]
@CynonMCC i have the same problem what should i do now
