### ISSUE TITLE
Mac - on opening jar file, really long warning appears. Game has disappeared. 

### ISSUE THREAD

**Issue by nousernamesavailable** [SheerSt/pokewilds#285]
![image](https://user-images.githubusercontent.com/38391149/201473896-978b0567-c8dd-4a6b-a951-5925a3181dd5.png)
This appears every time I open the jar file. There's an ok button, which then brings up the game. 

location does exist, contains save file (no error data though) 

It'd be neat if this wrapped around (:

**Comment by PigmyRhino** [comment]
Play this on my mac too, and agreed. it doesnt actually error. I havent had a problem with loading my file.

**Comment by nousernamesavailable** [comment]
Further update to this: my game did actually disappear. Request that the save be placed somewhere this doesn't happen.

**Comment by fourlastor** [comment]
@nousernamesavailable we're aware of the issue, we put the warning because unfortunately macos will delete the content of the folder only after a couple days from when you save. This will eventually be fixed, but for the time being the safest way is to follow the instructions in the readme:

## Mac

1. Requires Java to be installed: https://www.oracle.com/java/technologies/downloads/#jdk17-mac
2. In Finder, select the folder containing this readme, and on the top bar, click on "Finder", then "Services", then select "New Terminal at Folder".
3. Enter the following commands in the terminal:

```sh
cat mac-launcher.template > mac-launcher.command
chmod +x mac-launcher.command
```
Play the game by double-clicking `mac-launcher.command`.

You need to do this setup only once, then you can reuse the launcher you created
