### ISSUE TITLE
white sprite background in fight (for Volbeat atm)

### ISSUE THREAD

**Issue by ScarletBeastShow** [SheerSt/pokewilds#330]
I came to a situation when i had volbeatinvoled in a fight and it happens that there is no alpha background for it, it's a white square.

Might find other sprites and add it here later

![volbeat](https://user-images.githubusercontent.com/118899768/203537610-7dc1e666-c00f-43fc-bbf8-de31ca9e4279.png)

**Comment by fourlastor** [comment]
This is a known issue with mods that alter the battle background and some pokemon species (I think Unows have a similar issue), it won't be fixed in 0.8 (but we will do our best to fix this in future versions)

You should be able to work around it by adding in the transparent sprite for the mon as a mod
