### ISSUE TITLE
How to mute all sounds in PokeWilds

### ISSUE THREAD

**Issue by ghost** [SheerSt/pokewilds#358]
I know there is the muteMusic=true option which does indeed work but the bumps and cries are still coming through - I tried putting in muteSounds=true in the settings but no luck on that. What can I do?

**Comment by JENOVAAbsolute** [comment]
I do not think that is possible atm. Simply mute the game. If what you're trying to do is mute sounds so that you can get through dialogue faster (I do this when gathering items from my farms), that is possible. I simply unplugged my headset from my controller, and plugged it back in. If you don't use a headset or controller, you should be able to accomplish the same by going into your Windows sound settings and disabling your audio device with the game running. You can re-enable it immediately after.

**Comment by ghost** [comment]
Alright - I actually play on Mac and Mac does not have the Audio Mixer natively, for controlling specific application's volumes. I did however find a solution online that does the job but it would be nice to see this later if/when you guys work on the UI (a in-game Settings menu?)

**Comment by fourlastor** [comment]
> I did however find a solution online that does the job

which one? it would be nice to add it to the readme while we don't have it supported

>  would be nice to see this later if/when you guys work on the UI (a in-game Settings menu?)

Absolutely, this is planned

**Comment by ghost** [comment]
> which one? it would be nice to add it to the readme while we don't have it supported

I now use an external application (called SoundControl) that works similar to Windows' native Audio Mixer so I can turn down and on/off applications so it works great. It did cost 25$ after the initial trial since its too much to ask to make simple nice things free.

> Absolutely, this is planned

Awesome, glad to hear. Excited for the new major update whenever you guys push it out.
