### ISSUE TITLE
[Feature Request]: PORT TO GODOT ENGINE? 

### ISSUE THREAD

**Issue by killerdevildog11** [SheerSt/pokewilds#448]
### What would you like to request?

I AM WILLING TO PORT THIS TO THE GODOT ENGINE TO MAKE DEVELOPMENT EASIER AND MORE FEATURES... ANYONE ELSE WANT THIS? LET ME KNOW THANKS send me a message on discord. killerdevildog11

**Comment by coco875** [comment]
Why remade something who have been already done. It useless. By looking the repo pokewild is made with java and opengl so no need to remake the game with another engine

**Comment by HinataNekoNya** [comment]
> Why remade something who have been already done. It useless. By looking the repo pokewild is made with java and opengl so no need to remake the game with another engine 

I think you are right but at the same time you are wrong because on one point Java today and even with Minecraft has demonstrated the extent of its limits and why it no longer works.

 

On the other hand, I don't think Grogot is the solution to the problem, but I think that thinking about another engine that is more efficient over time and which remains multiplatform is not a bad thing.

**Comment by fourlastor** [comment]
We already discussed this internally  ~1-ish year ago and the TLDR is that it isn't happening, at least anytime soon.

Java works fine, while it has its obvious limitations, it also has a very mature library ecosystem, and it solves issues which other languages (namely C# and gdscript) can't really solve in a decent way right now.

One example is Java mods which can be controlled to the point of allowing or not classes to be loaded (so preventing malicious mods to say make any sort of I/O), you can definitely make "mods" with godot, but they'll be insecure and there isn't a clear and cut way to do so (while in java there is a very [mature solution](https://pf4j.org/) to it).

The other is frankly the community, I personally gave up on asking help for Godot because most of the time I just received no answer at all, on the other hand, the libgdx community has always been helpful, and that is something to consider when making a long-winded project, and most of the (actually useful) Godot knowledge is barred behind paywalls.
