### ISSUE TITLE
Pokémon not getting some moves

### ISSUE THREAD

**Issue by Mys73** [SheerSt/pokewilds#45]
So looking through some of the files, I noticed that some of my pokémon didn't learn moves on level up. According to Leafeon's evos_attacks.asm, it should learn a new move every 5 levels. Starting from lv 10 Eevee turned Leafeon, it only learned Synthesis, Giga Drain, and Sword's Dance. The leafeon is currently lv65. I missed Baby-Doll Eyes (lv15), Leech Seed (lv20), magical leaf (lv25), Sunny day (lv35), Leaf blade (lv50), and last resort (lv55). As well as any moves that might have been learned on evolution (I assume the db 0, [move name] is for just-hatched or evolution).

I also just caught a ditto (lv32) in a dungeon and it has no moves, which is interesting but most likely not intended.

I also have a Garchomp (raised from an wild egg) that missed Bulldoze, Dig, and sandstorm (not sure what else I missed due to evolutions changing when certain moves are learned).

**Comment by SheerSt** [comment]
Hi there @Mys73 - unfortunately many moves aren't implemented yet so that may be why. 

Also, the moves in evos_attacks.asm on the master branch have been updated since the release of v0.8.3. Here is a link to the movesets present in v0.8.3: https://github.com/SheerSt/pokemon-wilds/blob/v08-bugfixes/pokemon/evos_attacks.asm

In general there is an issue in v0.8.3 of pokemon not learning enough moves, I am working to improve that for the next release.

**Comment by Mys73** [comment]
I see, thanks for the info! I figured as much when some moves were missing (was wondering when Leafeon would get Leaf-blade, and just assumed it might not have been implemented). Finding this Github page and seeing the movelist made me think otherwise, though I think there might be some issues, as I do recall a wild pokemon using Bulldoze (while the Gible line didn't learn it).

**Comment by fourlastor** [comment]
Closing this as the work has been planned
