### ISSUE TITLE
opens but don't display game 

### ISSUE THREAD

**Issue by Nezzarn** [SheerSt/pokewilds#61]
I have tried all that I know what to do, but I can't seem to get the game to truly work.
When I open the game, it will open but it will not show the game in a window form nor will it go full screen, now it will play music but nothing else. please help me I would love to play and experience this game.

**Comment by SheerSt** [comment]
@Nezzarn If you open the app and music plays but the window isn't shown:

Hover over the icon on the task bar, right click the preview that pops up, and click maximize. If you don't want the window maximized, grab the top bar of the app and drag it down.

If you're still not able to get it working, can you join the PokeWilds discord so that someone can help you out? https://discord.gg/zzuVK8MdKK

**Comment by Nezzarn** [comment]
Thank you so much for your help it worked I was racking my brain on how to
play.

I will join the discord.

**Comment by fourlastor** [comment]
Closing as resolved
